### ISSUE TITLE
OpenID Verification Fails

### ISSUE THREAD

**Issue by michaelstonis** [waj/redmine_google_apps#1]
Attempting to login using my google account fails.

Clicking on the login account redirects me to the google authentication page. I enter in the appropriate authentication and then select to login. I am then redirected back to redmine authentication page and I receive the error "OpenID verification failed".

I tried installing the plugin openid fix (http://www.redmine.org/plugins/openid_fix) to see if that helped, but there was no change.

Are there any log files or additional information that I can provide?

**Comment by waj** [comment]
Did you check the production.log file to see if there is any other error? Your setup is probably failing to store the nonce generated for the OpenID authentication.

**Comment by waj** [comment]
Try running this on the Redmine directory:

```
rake open_id_authentication:db:create
```

That should generate the required tables for OpenID authentication. I probably missed this step in the documentation, as I configured my environment long long time ago.

**Comment by michaelstonis** [comment]
No luck. Same issues. Also ran rake db:migrate_plugins again as well, just as a check.

I checked the production log. There is the following error logged.

Error attempting to use stored discovery information: OpenID::TypeURIMismatch
Attempting discovery to verify endpoint
Performing discovery on http://testsite.com/openid?id=123123123123
Redirected to http://projects.testsite.com/login

Note: site and openid have been modified.

Something looks odd though when I search the output. Let's assume that the domain for verification is testsite.com. I successfully get redirected to the google apps authentication for testsite.com from the redmine authentication page. I am able to successfully enter in my google apps authentication and I am redirected back to redmine with the "OpenID verification failed" error message. If I look at the respose parameters, the key openid.claimed_id has a value like http://testsite.com/openid?id=123123123123. http://testsite.com is just a regular website and does not provide any openid authentication.

**Comment by waj** [comment]
I just found a quite silly mistake in the source code that prevented to create new users. Could you please pull and try again? If it doesn't work, please post your logs again. Thanks!

BTW, the OpenID URI is just an identifier. It's not meant to perform queries to that address, and the format of that URI depends on the OpenID provider. In this case, Google, uses the primary domain name appending /openid?id=123123...

**Comment by michaelstonis** [comment]
Unfortunately, it is coming up with the same error.

The openid result is returning with a status of failed. The returned attributes look like they sync up pretty close to a successful response shown at the [google openid site](http://code.google.com/apis/accounts/docs/OpenID.html).

It appears that this issue is maybe somewhat localized to google and happens with other languages as well. I found [the same or similar issue logged at the python-openid](https://github.com/adieu/python-openid/issues/1). I tried a few workarounds, but nothing seems to take. 

Which version of the ruby-openid gem are you using? I have 2.1.8 installed for my configuration. Also, are there any other configurations that you can think of that were possibly made or tweaked as part of the initial setup and configuration?

Thanks.

**Comment by waj** [comment]
Other people have been having the same issue and opened another ticket: https://github.com/waj/redmine_google_apps/issues/2. acdaniel actually found the reason of this common error.

Please, pull the new source code and install the gem 'ruby-openid-apps-discovery'. That should make the plugin work.

Thanks!
